theme: jekyll-theme-architect
title: Je commence Arduino
description: > # this means to ignore newlines until "baseurl:"
  Initiation à la plateforme Arduino...
collections:
  docs:
    output: true
    path: ""
